sweetbook_project/sweetbook/urls.py
from django.conf.urls import url
from sweetbook import views

app_name = 'sweetbook'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^recipes/(?P<recipe_slug>[\w\-]+)/$',
    	  views.chosen_recipe, name = 'chosen_recipe'),
    url(r'^events/(?P<event_slug>[\w\-]+)/$',
    	  views.chosen_event, name = 'chosen_event'),
    url(r'^recipes/', views.recipes, name = 'recipes'),
    url(r'^events/', views.events, name = 'events'),
    url(r'^add-to-cookbook', views.add_to_cookbook, name='add_to_cookbook'),
    url(r'^recipes/(?P<recipe_slug>[\w\-]+)/add-comment/$',views.add_comment, name = 'add_comment'),
    url(r'^myaccount/$', views.myaccount, name='myaccount'),
    url(r'^myaccount/delete-myaccount$', views.delete_myaccount, name='delete_myaccount'),
    url(r'^mybakebook/$', views.mybakebook, name='mybakebook'),
    url(r'^mycalendar/$', views.mycalendar, name='mycalendar'),
    url(r'^myrecipes/$', views.myrecipes, name='myrecipes'),
    url(r'^myrecipes/new-recipe/$', views.add_new_recipe, name='new_recipe'),
    url(r'^myrecipes/delete-recipe$', views.delete_recipe, name='delete_recipe'),
    url(r'^like-recipe/$', views.like_recipe, name='like_recipe'),
    url(r'^add-to-mycalendar', views.add_to_mycalendar, name='add_to_mycalendar'),
    url(r'^restricted/',views.restricted, name='restricted'),
    url(r'^register-profile/$', views.register_profile, name='register_profile'),
    url(r'^contactus/', views.contactus, name = 'contactus'),
]

sweetbook_project/sweetbook_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings 
from django.conf.urls.static import static
from sweetbook import views
from sweetbook.forms import UserProfileRegistrationForm 
from registration.backends.simple.views import RegistrationView
from django.urls import reverse


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('sweetbook:register_profile')

urlpatterns = [
	url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^sweetbook/', include('sweetbook.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sweetbook_project/sweetbook/forms.py
# implement the necessary infrastructure that will allow users to add recipes
# and comments to the database via forms
import django
import datetime
from django import forms
from sweetbook.models import Recipe, Comment, UserProfile
from django.contrib.auth.models import User
from registration.forms import RegistrationForm
from registration.forms import RegistrationFormUniqueEmail
import datetime
from django.utils import timezone
from datetime import datetime

class RecipeForm(forms.ModelForm,):
    # user = models.ForeignKey(User)
    name = forms.CharField(max_length=50,
                           help_text="Please enter the recipe name.")
    recipe_slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    picture = forms.ImageField(help_text="You can add pictures of your recipe.",
                               required=False)
    ingredients = forms.CharField(max_length=200,
                                  help_text="Enter the ingredients.")
    description = forms.CharField(max_length=400,
                                  help_text="Enter the description.")
    # HOW TO DO IT SO THAT THE USERS CAN RATE RECIPES?
    # rating = models.DecimalField(decimal_pla
    cooktime = forms.IntegerField(initial=0,
                                  help_text="Enter the cooktime.")
    difficulty = forms.CharField(max_length=10, initial ="medium",
                                  help_text="Enter the difficulty level.")
    last_modified = forms.DateTimeField(widget=forms.HiddenInput(), initial=django.utils.timezone.now)

    # an inline class to provide additional information on the form.
    class Meta:
        model = Recipe
        # exclude foreign key and rating
        exclude = ("user", "rating", "rating_number",)

class CommentForm(forms.ModelForm):
    # user = models.ForeignKey(User)
    # recipe = models.ForeignKey(Recipe)
    date = forms.DateTimeField(widget=forms.HiddenInput(), initial=django.utils.timezone.now)
    description = forms.CharField(max_length=100,
                                  help_text="Enter your comment.")
    # an inline class to provide additional information on the form.
    class Meta:
        model = Comment
        # exclude foreign keys
        exclude = ("user", "recipe")


'''
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email','password')

class UserProfileForm(forms.ModelForm):

  # not sure if we need to write the fields, in the book they don t
  # check at testing
  #-------------fields--------#

    class Meta:
        model = UserProfile
        exclude = ('user',)

        '''

class UserProfileRegistrationForm(forms.ModelForm,):
    firstname = forms.CharField(max_length = 25,required=True)
    surname = forms.CharField(max_length = 25,required=True)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user','events',)

sweetbook_project/sweetbook/views.py
import os
from datetime import datetime

os.environ.setdefault('DJANGO_SETTINGS_MODULE',
                      'sweetbook_project.settings')

import django
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.db.models import Count
from django import forms
from django.contrib.auth.models import User
from sweetbook.models import User, Event, Recipe, SavedRecipe, Comment
from sweetbook.forms import CommentForm, RecipeForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from sweetbook.forms import UserProfileRegistrationForm
from sweetbook.models import UserProfile
from datetime import datetime
from django.views.decorators.csrf import requires_csrf_token
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt,csrf_protect,ensure_csrf_cookie
'''
Cookies helper functions which help storing cookies on the server side
Number of cookies are stored and displayed in the home page

'''

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time=datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    # get cookies from the last day
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits']= visits


'''
Home view returns to the template:
- a list of 10 top rated recipes
- the recipe of the day ( count a recently added recipe with the biggest number of comments)
- the latest events, in the date order (the first event is the closest to present moment)

'''
def home(request):

    top_rated_recipes = Recipe.objects.order_by('rating')[::-1][:10]      # top rated recipes

    # find out the most commented recipe from the last 5 recipes added recently
    most_commented_recipes= []
    context_dict = {}

    for recipe in Recipe.objects.order_by('last_modified')[:5]:
        comments_count = recipe.comment_set.count()                       # add the recipes to a list containing the number of comments as well
        most_commented_recipes.append([comments_count,recipe])
    most_commented_recipes.sort(key=lambda x: x[0])                       # sort the list

    if len(most_commented_recipes) > 0:
        recipe_of_the_day = most_commented_recipes[0][1]                  # get the first element of the sorted list
        context_dict ["recipeofday"] = recipe_of_the_day

    latest_events = Event.objects.filter().order_by('date')[:10]

    # add to context dictionary
    context_dict ["toprated"] = top_rated_recipes
    context_dict ["latestevents"] = latest_events

    # count the visits
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    # let tamplate handle the presentation of data
    response = render(request, 'sweetbook/home.html', context=context_dict)
    return response


'''
Recipes view will return to template:

- a list of the recently added(or modified) recipes

'''
def recipes(request):

    context_dict={}
    last_recipes = Recipe.objects.order_by('last_modified')[:20]
    context_dict["recipes"] = last_recipes

    return render(request, 'sweetbook/recipes.html', context_dict)

'''
chosen-recipe view will return to template:

- the recipe that the user wants to access
- the comments that other users made on the recipe
- the user that created the recipe

'''
@csrf_exempt
def chosen_recipe(request, recipe_slug):

    context_dict = {}
    try:
        # get the information about recipe, comments, user
        recipe = Recipe.objects.get(recipe_slug=recipe_slug)
        comments = Comment.objects.filter (recipe = recipe)
        user = User.objects.filter ( recipe = recipe)

        # store them in the context dictionary,if found
        context_dict['comments'] = comments
        context_dict['recipe'] = recipe
    except Recipe.DoesNotExist:
        context_dict['comments'] = None
        context_dict['recipe'] = None

    return render (request, 'sweetbook/chosen_recipe.html', context_dict)

'''
contactus view will return to template and empty dictionary

'''
def contactus(request):
	return render (request, 'sweetbook/contactus.html',{})


'''
add-comment view which will deal with receives a POST request and stores the given details in the database

'''
@login_required
# @requires_csrf_token
@csrf_exempt
@ensure_csrf_cookie
def add_comment(request, recipe_slug):
    try:
        # get the recipe from the recipe slug
        recipe = Recipe.objects.get(recipe_slug = recipe_slug)
    except Recipe.DoesNotExist:
        recipe = None
        user = None

    # get the user
    if request.user.is_authenticated():
        user = request.user

    if request.method == 'POST':

        # if it was  POST request, get the text message and save the new comment
        comment_text = request.POST.get('text')
        if recipe and user:
            comment = Comment.get_or_create(user = user, recipe = recipe, description = text)
            comment.save()
            # return chosen_recipe(request, recipe_slug)
            #return render (request, 'sweetbook/ad.html', context_dict)
            return chosen_recipe(request, recipe.recipe_slug)

    context_dict = {'form':form, 'recipe':recipe}
    return render (request, 'sweetbook/add_comment.html', context_dict)

'''
add-new-recipe view gets a form from the user, and saves a the recipe in the database

'''
@login_required
def add_new_recipe(request):
    user = None
    if request.user.is_authenticated():
        user = request.user

    form = RecipeForm()
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save (commit=False)
            recipe.user = user
            recipe.save()
            return chosen_recipe(request, recipe.recipe_slug)
        else:
            print(form.errors)

    context_dict = {'form':form}
    return render (request, 'sweetbook/new_recipe.html', context_dict)

'''
events view - returns to the template:
    - a list of all events, ordered by date

'''
def events (request):
    context_dict = {}
    latest_events = Event.objects.order_by('date')[:10]
    context_dict["events"] = latest_events
    return render(request, 'sweetbook/events.html', context_dict)


'''
chosen-event view - returns to the template:
    - the event that is requested using the event_slug
'''

def chosen_event(request, event_slug):
    context_dict = {}
    try:
        event = Event.objects.get(event_slug=event_slug)
        context_dict['event'] = event
    except Category.DoesNotExist:
        context_dict['event'] = None
    return render (request, 'sweetbook/chosen_event.html', context_dict)


'''
add-to-cookbook view
    - take the recipe_id from GET request
    - finds out the recipe associated with it
    - uses the SavedRecipe method to store it in the database
(SavedRecipe contains the recipes created by other users, but which want to be stored by the current user on his profile)

'''
@login_required
def add_to_cookbook(request):
	# add a recipe to the user cookbook
    user = None

    if request.user.is_authenticated():
        user = request.user

    recipe_id = None
    if request.method == "GET" and user:
        recipe_id = request.GET['recipe_id']                    # get the recipe_id
        if recipe_id:
            recipe = Recipe.objects.get(id = int(recipe_id))
            if recipe:
                # save the recipe in the database
                saved_recipe = SavedRecipe.objects.get_or_create(recipe = recipe, user=user)[0]
                saved_recipe.save()

    return HttpResponse(saved_recipe)


'''
add-to-mycalendar view:
    - takes an event_id using the GET request
    - find out what the current event is
    - stores the event in the current users' s profile ( visible in the /mycalendar/ page)

'''

@login_required
def add_to_mycalendar(request):
    user = None
    user_profile = None

    if request.user.is_authenticated():
        user = request.user
        user_profile = get_object_or_404(UserProfile, user=user)

    event_id = None
    if request.method == "GET" and user:
        event_id = request.GET['event_id']
        if event_id:
            event = Event.objects.get(id = int(event_id))
            if event:
                user_profile.events.add(event)
                user_profile.save()
    return HttpResponse(event)


'''
like-recipe view:
    - get the receipe_id using the GET request
    - gets the value given also through the GET request (which is either 1,2,3,4,5)
    - computes the average

'''
@login_required
def like_recipe(request):
    rec_id = None
    if request.method == 'GET':
        rec_id = request.GET['recipe_id']
        rec_value = request.GET['recipe_value']

    rating = 0

    if rec_id:
        rec = Recipe.objects.get(id=int(rec_id))
        if rec:

            # if the rating of the recipe is 0, the rating average will be the first rating
            if rating == 0:
                rating = float(rec_value)
            else:
                rating = (float(rec.rating) + float(rec_value))/2
            rec.rating =  rating
            rec.save()

    return HttpResponse(rating)


'''
myaccount view - returns to the template:
    - the information about the user (username)
    - the information about his profile (surname, firstname, picture)
'''

@login_required

sweetbook_project/templates/sweetbook/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
	<head lang="en">
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href = "{% static 'images/icon.jpg' %}" rel="icon" type="image/jpg">

		<!--stylesheets-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
		{% if user.is_authenticated %}
			<link rel="stylesheet" type="text/css" href="{% static 'css/base-user.css' %}">
		{% endif %}

		{% block style_block %}
		{% endblock %}

		<!--title-->
		<title>
			SweetBook -
			{% block title_block %}
			{% endblock %}
		</title>

	</head>

	<body>
		<!--logo picture with login, sign in and log out buttons-->
		<div>
			<a href="{% url 'sweetbook:home' %}"><img id="logo" src="{% static 'images/logo.jpg' %}" alt="Logo of Web" /></a>
			<div id="topbarright">
				{% if user.is_authenticated %}
					<p>
						Hello {{user}}
            			<button onclick="visitPage('{% url 'auth_logout' %}');">Log out</button>
					</p>
				{% else %}
					<p id="or">
						<button onclick="visitPage('{% url 'registration_register' %}');">Sign up</button>
						OR
						<button onclick="visitPage('{% url 'auth_login' %}');">Log in</button>
					</p>
				{% endif %}
			</div>
		</div>

		<!--menu buttons-->
		<div id="menu">
			<button onclick="visitPage('{% url 'sweetbook:home' %}');">Home</button>
			<button onclick="visitPage('{% url 'sweetbook:recipes' %}');">Recipes</button>
			<button onclick="visitPage('{% url 'sweetbook:events' %}');">Events</button>
			<button onclick="visitPage('{% url 'sweetbook:contactus' %}');">Contact us</button>
			{% if user.is_authenticated %}
				<button onclick="visitPage('{% url 'sweetbook:myaccount' %}');">My Account</button>
			{% endif %}
		</div>

		{% block body_block %}
		{% endblock %}

		<!--copyrights line-->
		<p id="rights">Team D ©Copyrights 2019, All rights Reserved </p>

		<!--scripts-->
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
		<script src="{% static "js/jquery.js" %}"></script>
    	<script src="{% static "js/sweetbook-ajax.js" %}"></script>
		<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
		{% block script_block%}
		{% endblock %}
	</body>
</html>

sweetbook_project/templates/sweetbook/events.html
{% extends 'sweetbook/base.html' %}
{% load staticfiles %}

{% block style_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/events.css' %}">
{% endblock %}

<!--title-->
{% block title_block %}
	Events
{% endblock %}

{% block body_block %}
	{% if events %}
		{% for event in events %}
			<!--main box of each event-->
			<div class="container orange-container hundred-width">
				<img src="{% static 'images/' %}{{event.event_slug}}.jpg" class="googleMap black-container" alt="Map of Event" />
				<!--description of each event-->
				<p class="content">
					<span class="content-header">{{event.name}}</span><br><br>
					<img class="cooks-image" src="{% static 'images/cooks.jpg' %}">
					<b>Date: </b>{{event.date}}<br>
					<b>Place: </b>{{event.place}}<br>
					<b>Postcode: </b>{{event.postcode}}<br><br>
					<a href="{% url 'sweetbook:chosen_event' event.event_slug %}">See more</a>
				</p>
			</div>
		{% endfor %}
	{% else %}
		<!--if no events-->
		<div id="no-events" class="orange-container hundred-width center">No events to be shown.</div>
	{% endif %}
{% endblock %}

sweetbook_project/templates/sweetbook/home.html
{% extends 'sweetbook/base.html' %}
{% load staticfiles %}

{% block style_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
{% endblock %}

<!--title-->
{% block title_block %}
	Home
{% endblock %}

{% block body_block %}
	<!--Search form-->
	<div id="visits" class="orange-container">
		Visits of the page: {{visits}}
	</div>

	<!--Header of top rated-->
	<p id="topratedhead" class="orange-container">Top rated <span id="stars">★★★★★</span></p>

	<!--Taken from page: http://www.optimalmatching.com/MATCHUP2019/-->
	<!--Slideshow-->
    <div id="myCarousel" class="carousel slide orange-container" data-ride="carousel">
    	{% if toprated %}
	        <!-- Carousel indicators -->
	        <ol class="carousel-indicators">
	        	{% for recipe in toprated %}
	        		{% if forloop.first %}
	        			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
	        		{% else %}
	        			<li data-target="#myCarousel" data-slide-to="{{forloop.counter0}}"></li>
	        		{% endif %}
	            {% endfor %}
	        </ol>

	        <!-- Wrapper for carousel items -->
	        <div class="carousel-inner">
	        	{% for recipe in toprated %}
	        		{% if forloop.first %}
	        			<div class="item active">
							<div class="item-text orange-container">{{recipe.name}}<br>Rating: {{recipe.rating}}<span><a href="{% url 'sweetbook:chosen_recipe' recipe.recipe_slug %}">Go to the recipe</a></span></div>
							<img class="item-image" src="{{MEDIA_URL}}{{recipe.picture}}" alt="{{recipe.name}}" onerror="this.onerror=null;this.src='{% static 'images/default.jpg' %}';">
						</div>
					{% else %}
						<div class="item">
							<div class="item-text orange-container">{{recipe.name}}<br>Rating: {{recipe.rating}}<span><a href="{% url 'sweetbook:chosen_recipe' recipe.recipe_slug %}">Go to the recipe</a></span></div>
							<img class="item-image" src="{{MEDIA_URL}}{{recipe.picture}}" alt="{{recipe.name}}" onerror="this.onerror=null;this.src='{% static 'images/default.jpg' %}';">
						</div>
	        		{% endif %}
				{% endfor %} 
	        </div> 

	        <!-- Carousel controls -->
	        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
	            <span class="glyphicon glyphicon-chevron-left"></span>
	        </a>
	        <a class="carousel-control right" href="#myCarousel" data-slide="next">
	            <span class="glyphicon glyphicon-chevron-right"></span>
	        </a>
        {% else %}
			<div class="center"> No top-rated recipes to be shown.</div>
		{% endif %}
    </div>

	<!--Recipe of the day-->
	<div id="recipeofday">
		<div id="header-recipe" class="orange-container">Recipe of the Day</div>
		<div id="container-recipe" class="orange-container hundred-width">
			{% if recipeofday %}
				<img class="black-container" src="{{MEDIA_URL}}{{recipeofday.picture}}" alt="{{recipeofday.name}}" onerror="this.onerror=null;this.src='{% static 'images/default.jpg' %}';">
				<p class="black-container"><b>{{recipeofday.name}}</b><br/>{{recipeofday.description | truncatechars:220}}<a href="{% url 'sweetbook:chosen_recipe' recipeofday.recipe_slug %}">See more</a></p>
			{% else %}
				<p class="center">No recipe of the day.</p>
			{% endif %}
		</div>
	</div>

	<!--Latest events-->
	<div id="latestevents">
		<div id="header-event" class="orange-container">Latest Events</div>
		<div id="container-event" class="orange-container hundred-width">
			{% if latestevents %}
				<ul>
				{%for event in latestevents %}
					<li>{{event.name}} - <a href="{% url 'sweetbook:chosen_event' event.event_slug %}">See more</a></li>
				{% endfor %}
				</ul>
			{% else %}
				<p class="center">No latest events to be shown.</p>
			{% endif %}
		</div>
	</div>
		<img id="characters" src="{% static 'images/characters.png' %}" alt="Cartoon bakers">

	</div>

{% endblock %}

{% block script_block %}
	<!--scripts taken from page defined above to create slideshow-->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% endblock %} 

sweetbook_project/templates/sweetbook/myaccount.html
{% extends 'sweetbook/base.html' %}
{% load staticfiles %}

{% block style_block %}
	  <link rel="stylesheet" type="text/css" href="{% static 'css/myaccount.css' %}">
	  {% block child_style_block %}
	  {% endblock %}
{% endblock %}

<!--title-->
{% block title_block %}
	My Account
{% endblock %}

{% block body_block %}
		<!--buttons for user-->
		<div id="headers">
			<button class="orange-container" id="myaccount" onclick="visitPage('{% url 'sweetbook:myaccount' %}');">My Account</button>
			<button class="orange-container" id="mybakebook" onclick="visitPage('{% url 'sweetbook:mybakebook' %}');">My Bakebook</button>
			<button class="orange-container" id="mycalendar" onclick="visitPage('{% url 'sweetbook:mycalendar' %}');">My Calendar</button>
			<button class="orange-container" id="myrecipes" onclick="visitPage('{% url 'sweetbook:myrecipes' %}');">My Recipes</button>
		</div>

		<div id="content" class="orange-container hundred-width">
			{% block content_block %}
			<!--profile picture-->
			<img id="content-left" class="black-container" src="{{MEDIA_URL}}{{userprofile.picture}}" alt="Profile picture" onerror="this.onerror=null;this.src='{% static 'images/default-profile.jpg' %}';">

			<!--description-->
			<div id="content-right">
				<table>
					<tr>
						<td class="head">Username:</td>
						<td>{{user.username}}</td>
					</tr>
					<tr>
						<td class="head">First name(s):</td>
						<td>{{userprofile.firstname}}</td>
					</tr>
					<tr>
						<td class="head">Surname:</td>
						<td>{{userprofile.surname}}</td>
					</tr>
					<tr>
						<td class="head">Email:</td>
						<td>{{user.email}}</td>
					</tr>
				</table>

				<!--button delete-->
				<div class="hundred-width" >
					<img src="{% static 'images/boy.jpg' %}" alt="Cook Boy">
					<button onclick="visitPage('{% url 'sweetbook:delete_myaccount' %}'); alert('Your account was deleted');">Delete Account</button>
          			<img src="{% static 'images/girl.jpg' %}" alt="Cook Girl">
				</div>
			</div>
			{% endblock %}
		</div>

{% endblock %}

sweetbook_project/templates/sweetbook/mybakebook.html
{% extends 'sweetbook/myaccount.html' %}
{% load staticfiles %}

{% block child_style_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/mybakebook.css' %}">
{% endblock %}

{% block title_block %}
	My Bakebook
{% endblock %}

{% block content_block %}
	{% if mybakebook %}
		<div id="main-box">
		{% for recipe in mybakebook %}
			<div class="container black-container">
				<!--recipe picture-->
				<img class="image black-container" src="{{MEDIA_URL}}{{recipe.picture}}" alt="{{recipe.name}}" onerror="this.onerror=null;this.src='{% static 'images/default.jpg' %}';">
				<!--recipe description-->
				<p class="content">
					<span class="content-header">{{recipe.name}}</span><br><br>
					<img class="girl-image" src="{% static 'images/girl.jpg' %}">
					<a href="{% url 'sweetbook:chosen_recipe' recipe.recipe_slug %}">Go to recipe</a>
				</p>
			</div>
		{% endfor %}
		</div>
	{% else %}
		<div class="center">No saved recipes in My BakeBook.</div>
	{% endif %}
{% endblock %}

sweetbook_project/templates/sweetbook/myrecipes.html
{% extends 'sweetbook/myaccount.html' %}
{% load staticfiles %}

{% block child_style_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/mybakebook.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/myrecipes.css' %}">
{% endblock %}

{% block title_block %}
	My Recipes
{% endblock %}

{% block content_block %}
	<!--btuuon to add new recipe-->
	<button id="add-new-recipe" onclick="visitPage('{% url 'sweetbook:new_recipe' %}');">Add New Repice</button>

	{% if myrecipes %}
		<div id="main-box">
		{% for recipe in myrecipes %}

			<div class="container black-container">
				<!--recipe picture-->
				<img class="image black-container" src="{{MEDIA_URL}}{{recipe.picture}}" alt="{{recipe.name}}" onerror="this.onerror=null;this.src='{% static 'images/default.jpg' %}';">
				<!--recipe description-->
				<p class="content">
					<span class="content-header">{{recipe.name}}</span><br><br>
					<img class="girl-image" src="{% static 'images/girl.jpg' %}">
					<a href="{% url 'sweetbook:chosen_recipe' recipe.recipe_slug %}">Go to recipe</a><br><br>
					<button id="delete-recipe" data-recid="{{recipe.id}}">Delete Recipe</button>
				</p>
			</div>
			
		{% endfor %}
		</div>
	{% else %}
		<div class="center">No added recipes in My Recipes.</div>
	{% endif %}

{% endblock %}